/**
 * Shared emitter infrastructure: generated-file shape, expression typing,
 * constant folding, and small text utilities.
 */

import type { Expr } from "../domain/expr";
import type { BrickDef, PartDef, PropDef, RecordTypeDef } from "../domain/model";

export interface GeneratedFile {
  /** Path relative to the output root, e.g. `ui/button/button.tsx`. */
  path: string;
  contents: string;
}

export type EmitterRuntime = "templ" | "react" | "svelte" | "vue" | "latte" | "twig";

export interface Emitter {
  readonly runtime: EmitterRuntime;
  emit(brick: BrickDef): GeneratedFile[];
}

export const BANNER = "Code generated by @ui8kit/codegen. DO NOT EDIT.";

// ---------------------------------------------------------------------------
// Expression typing
// ---------------------------------------------------------------------------

export type ExprType = "string" | "bool" | "int";

export interface TypeEnv {
  part: PartDef;
  records: RecordTypeDef[];
  /** Record type of the enclosing forEach, when inside one. */
  itemRecord?: RecordTypeDef;
}

export function propDef(part: PartDef, name: string): PropDef {
  const p = part.props.find((x) => x.name === name);
  if (!p) throw new Error(`${part.name}: unknown prop ${name}`);
  return p;
}

/**
 * Build the typing environment for a part. Parts have at most one `items`
 * prop, so its record doubles as the loop-item record for expression typing.
 */
export function makeEnv(brick: { recordTypes?: RecordTypeDef[] }, part: PartDef): TypeEnv {
  const records = brick.recordTypes ?? [];
  const itemsProp = part.props.find((p) => p.type === "items");
  const itemRecord = itemsProp ? records.find((r) => r.name === itemsProp.itemsOf) : undefined;
  return { part, records, itemRecord };
}

export function exprType(expr: Expr, env: TypeEnv): ExprType {
  switch (expr.kind) {
    case "lit":
      return typeof expr.value === "boolean" ? "bool" : typeof expr.value === "number" ? "int" : "string";
    case "prop": {
      const p = propDef(env.part, expr.name);
      if (p.type === "string" || p.type === "bool" || p.type === "int") return p.type;
      throw new Error(`${env.part.name}: prop ${expr.name} of type ${p.type} not usable in expressions`);
    }
    case "item": {
      const record = env.itemRecord;
      if (!record) throw new Error(`${env.part.name}: item ref outside forEach`);
      const f = record.fields.find((x) => x.name === expr.field);
      if (!f) throw new Error(`${env.part.name}: record ${record.name} has no field ${expr.field}`);
      return f.type;
    }
    case "derivedRef": {
      const d = env.part.derived?.[expr.name];
      if (!d) throw new Error(`${env.part.name}: unknown derived ${expr.name}`);
      return exprType(d, env);
    }
    case "resolvedTag":
    case "defaultIfEmpty":
    case "mapOr":
    case "intMapOr":
    case "concat":
    case "boolToString":
    case "intToString":
      return "string";
    case "cond":
      return exprType(expr.then, env);
    case "eq":
    case "and":
    case "or":
    case "not":
    case "isSet":
    case "contains":
      return "bool";
  }
}

/** True when the expression (transitively) references the loop item. */
export function usesItem(expr: Expr, env: TypeEnv): boolean {
  switch (expr.kind) {
    case "item":
      return true;
    case "derivedRef": {
      const d = env.part.derived?.[expr.name];
      return d ? usesItem(d, env) : false;
    }
    default:
      break;
  }
  const children = childListOf(expr);
  return children.some((c) => usesItem(c, env));
}

/** True when the expression (transitively) references a component prop. */
export function usesProps(expr: Expr, env: TypeEnv): boolean {
  switch (expr.kind) {
    case "prop":
      return true;
    case "derivedRef": {
      const d = env.part.derived?.[expr.name];
      return d ? usesProps(d, env) : false;
    }
    default:
      break;
  }
  return childListOf(expr).some((c) => usesProps(c, env));
}

function childListOf(expr: Expr): Expr[] {
  switch (expr.kind) {
    case "lit":
    case "prop":
    case "item":
    case "derivedRef":
    case "resolvedTag":
      return [];
    case "defaultIfEmpty":
    case "mapOr":
    case "intMapOr":
    case "not":
    case "isSet":
    case "contains":
    case "boolToString":
    case "intToString":
      return [expr.expr];
    case "cond":
      return [expr.test, expr.then, expr.else];
    case "eq":
      return [expr.left, expr.right];
    case "and":
    case "or":
      return expr.exprs;
    case "concat":
      return expr.parts;
  }
}

/**
 * Replace `resolvedTag` with a literal and fold trivially-constant boolean
 * algebra. Used by the Templ emitter inside tag-switch cases, where the
 * resolved tag is a known literal per case.
 */
export function foldResolvedTag(expr: Expr, tag: string): Expr {
  const fold = (e: Expr): Expr => {
    switch (e.kind) {
      case "resolvedTag":
        return { kind: "lit", value: tag };
      case "eq": {
        const left = fold(e.left);
        const right = fold(e.right);
        if (left.kind === "lit" && right.kind === "lit") {
          return { kind: "lit", value: left.value === right.value };
        }
        return { ...e, left, right };
      }
      case "and": {
        const exprs = e.exprs.map(fold);
        if (exprs.some((x) => x.kind === "lit" && x.value === false)) return { kind: "lit", value: false };
        const rest = exprs.filter((x) => !(x.kind === "lit" && x.value === true));
        if (rest.length === 0) return { kind: "lit", value: true };
        if (rest.length === 1) return rest[0]!;
        return { ...e, exprs: rest };
      }
      case "or": {
        const exprs = e.exprs.map(fold);
        if (exprs.some((x) => x.kind === "lit" && x.value === true)) return { kind: "lit", value: true };
        const rest = exprs.filter((x) => !(x.kind === "lit" && x.value === false));
        if (rest.length === 0) return { kind: "lit", value: false };
        if (rest.length === 1) return rest[0]!;
        return { ...e, exprs: rest };
      }
      case "not": {
        const inner = fold(e.expr);
        if (inner.kind === "lit" && typeof inner.value === "boolean") {
          return { kind: "lit", value: !inner.value };
        }
        return { ...e, expr: inner };
      }
      case "cond": {
        const test = fold(e.test);
        if (test.kind === "lit" && typeof test.value === "boolean") {
          return test.value ? fold(e.then) : fold(e.else);
        }
        return { ...e, test, then: fold(e.then), else: fold(e.else) };
      }
      case "defaultIfEmpty":
        return { ...e, expr: fold(e.expr) };
      case "mapOr":
        return { ...e, expr: fold(e.expr) };
      case "intMapOr":
        return { ...e, expr: fold(e.expr) };
      case "isSet":
        return { ...e, expr: fold(e.expr) };
      case "contains":
        return { ...e, expr: fold(e.expr) };
      case "boolToString":
        return { ...e, expr: fold(e.expr) };
      case "intToString":
        return { ...e, expr: fold(e.expr) };
      case "concat":
        return { ...e, parts: e.parts.map(fold) };
      default:
        return e;
    }
  };
  return fold(expr);
}

// ---------------------------------------------------------------------------
// Text utilities
// ---------------------------------------------------------------------------

export function indent(text: string, level: number, unit = "  "): string {
  const pad = unit.repeat(level);
  return text
    .split("\n")
    .map((line) => (line.trim() === "" ? line : pad + line))
    .join("\n");
}

export function pascalCase(kebab: string): string {
  return kebab
    .split(/[-_.]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

export function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

export function jsString(value: string): string {
  return JSON.stringify(value);
}

/** Recipe variable/const name from the variants.json file stem. */
export function recipeVarName(recipeFile: string): string {
  const stem = recipeFile.replace(/\.variants\.json$/, "");
  return pascalCase(stem) + "Variants";
}
