// Code generated by tagsgen. DO NOT EDIT.

import { isDevEnv } from "./env";

export const TagGroup = {
  Layout: "Layout",
  BoxAllowed: "BoxAllowed",
  BlockText: "BlockText",
  Inline: "Inline",
  Heading: "Heading",
  List: "List",
  ListItem: "ListItem",
  Form: "Form",
  FormControl: "FormControl",
  FormLabel: "FormLabel",
  Table: "Table",
  TableSection: "TableSection",
  TableRow: "TableRow",
  TableCell: "TableCell",
  TableColumn: "TableColumn",
  Media: "Media",
  Disclosure: "Disclosure",
  Container: "Container",
  Stack: "Stack",
  Group: "Group",
  Text: "Text",
} as const;

export type TagGroup = (typeof TagGroup)[keyof typeof TagGroup];

const layoutTags = new Set(["div", "section", "article", "aside", "header", "footer", "main", "nav", "figure", "search", "hgroup"]);
const boxAllowedTags = new Set(["div"]);
const blockTextTags = new Set(["p", "blockquote", "figcaption", "address", "pre"]);
const inlineTags = new Set(["span", "em", "strong", "small", "abbr", "cite", "code", "kbd", "mark", "time", "data", "var", "samp", "sub", "sup", "b", "i", "u", "s", "q", "dfn", "bdo", "bdi", "ins", "del"]);
const headingTags = new Set(["h1", "h2", "h3", "h4", "h5", "h6"]);
const listTags = new Set(["ul", "ol", "dl", "menu"]);
const listItemTags = new Set(["li", "dt", "dd"]);
const formTags = new Set(["form", "fieldset"]);
const formControlTags = new Set(["input", "textarea", "select", "button", "option", "optgroup", "datalist", "output", "meter", "progress"]);
const formLabelTags = new Set(["label", "legend"]);
const tableTags = new Set(["table"]);
const tableSectionTags = new Set(["thead", "tbody", "tfoot"]);
const tableRowTags = new Set(["tr"]);
const tableCellTags = new Set(["th", "td"]);
const tableColumnTags = new Set(["colgroup", "col"]);
const mediaTags = new Set(["img", "picture", "source"]);
const disclosureTags = new Set(["details", "summary"]);
const containerTags = new Set(["div", "main", "section"]);
const stackTags = new Set(["div", "ul", "ol"]);
const groupTags = new Set(["div", "fieldset", "dl"]);

function oneOf(tag: string, options: Set<string>): boolean {
  return options.has(tag);
}

const warnedTagFallbacks = new Set<string>();

function warnTagFallback(tag: string, fallback: string, group: TagGroup): void {
  if (!isDevEnv()) return;
  const key = `${group}:${tag}:${fallback}`;
  if (warnedTagFallbacks.has(key)) return;
  warnedTagFallbacks.add(key);
  console.warn(`[resolveTag] disallowed tag "${tag}" for group "${group}", fallback "${fallback}" used.`);
}

export function isAllowedTag(tag: string, group: TagGroup): boolean {
  const t = tag.trim().toLowerCase();
  switch (group) {
    case TagGroup.Layout:
      return oneOf(t, layoutTags);
    case TagGroup.BoxAllowed:
      return oneOf(t, boxAllowedTags);
    case TagGroup.BlockText:
      return oneOf(t, blockTextTags);
    case TagGroup.Inline:
      return oneOf(t, inlineTags);
    case TagGroup.Heading:
      return oneOf(t, headingTags);
    case TagGroup.List:
      return oneOf(t, listTags);
    case TagGroup.ListItem:
      return oneOf(t, listItemTags);
    case TagGroup.Form:
      return oneOf(t, formTags);
    case TagGroup.FormControl:
      return oneOf(t, formControlTags);
    case TagGroup.FormLabel:
      return oneOf(t, formLabelTags);
    case TagGroup.Table:
      return oneOf(t, tableTags);
    case TagGroup.TableSection:
      return oneOf(t, tableSectionTags);
    case TagGroup.TableRow:
      return oneOf(t, tableRowTags);
    case TagGroup.TableCell:
      return oneOf(t, tableCellTags);
    case TagGroup.TableColumn:
      return oneOf(t, tableColumnTags);
    case TagGroup.Media:
      return oneOf(t, mediaTags);
    case TagGroup.Disclosure:
      return oneOf(t, disclosureTags);
    case TagGroup.Container:
      return oneOf(t, containerTags);
    case TagGroup.Stack:
      return oneOf(t, stackTags);
    case TagGroup.Group:
      return oneOf(t, groupTags);
    case TagGroup.Text:
      return blockTextTags.has(t) || inlineTags.has(t);
    default:
      return false;
  }
}

export function resolveTag(tag: string | undefined, fallback: string, group: TagGroup): string {
  const t = tag?.trim().toLowerCase() ?? "";
  if (!t) return fallback;
  if (isAllowedTag(t, group)) return t;
  warnTagFallback(t, fallback, group);
  return fallback;
}
