import {
  attrBool,
  attrClass,
  attrExpr,
  attrRest,
  brick,
  cond,
  controlPassthroughProps,
  el,
  fwd,
  intToString,
  isSet,
  lit,
  pAttrs,
  pBool,
  pClass,
  pInt,
  pPass,
  prop,
  pSize,
  pStr,
  pVariant,
  text,
} from "../_dsl";
import textareaVariants from "./textarea.variants.json";

export default brick({
  id: "ui.textarea",
  dir: "textarea",
  docs: "Textarea is a multi-line native text field with row sizing.",
  recipes: { textarea: { file: "textarea.variants.json", recipe: textareaVariants } },
  parts: [
    {
      name: "Textarea",
      docs: "Textarea renders a styled multi-line form control.",
      recipeId: "textarea",
      classes: { recipe: { variant: "Variant", size: "Size" } },
      props: [
        pVariant(),
        pSize(),
        pClass(),
        pPass("Name"),
        pStr("Value", "initial textarea content"),
        pPass("Placeholder"),
        pInt("Rows", "visible line count; defaults to 4 when zero"),
        pBool("Disabled"),
        pBool("Required"),
        ...controlPassthroughProps(),
        pAttrs(),
      ],
      render: el(
        "textarea",
        [
          fwd("id", "ID"),
          fwd("name", "Name"),
          attrClass(),
          attrExpr("rows", cond(isSet(prop("Rows")), intToString(prop("Rows")), lit("4"))),
          fwd("placeholder", "Placeholder"),
          attrBool("disabled", prop("Disabled")),
          attrBool("required", prop("Required")),
          fwd("role", "Role"),
          fwd("tabindex", "TabIndex"),
          fwd("aria-label", "AriaLabel"),
          attrRest(),
        ],
        [text(prop("Value"))]
      ),
    },
  ],
});
