/**
 * Latte theme bundle — emit only Latte templates + PHP runtime into a
 * consumer directory (e.g. wp-fasty `.workspaces/ui8kit-latte`).
 *
 * Unlike `generate --runtimes latte`, this profile:
 * - skips parity harnesses (`cmd/parity-latte`)
 * - emits a Latte-only `composer.json` (no Twig)
 * - writes `manifest.json` with coverage / skip summary
 *
 * Usage:
 *   bun src/application/generate-latte-bundle.ts [--out <dir>]
 */

import { bricks } from "../../bricks/index";
import { emitLatteBundleComposerJson } from "../emitters/php-harness";
import { BANNER } from "../emitters/common";
import { generateFiles, phpSkippedParts, writeFiles } from "./generate";

function parseOut(args: string[]): string {
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--out" && args[i + 1]) return args[++i]!;
  }
  return "generated/latte-bundle";
}

function emitManifest(): { path: string; contents: string } {
  const skipped = phpSkippedParts(bricks);
  const total = bricks.reduce((n, b) => n + b.parts.length, 0);
  const manifest = {
    generator: "@ui8kit/codegen",
    runtime: "latte",
    banner: BANNER,
    bricks: bricks.length,
    parts: {
      total,
      generated: total - skipped.length,
      skipped: skipped.length,
    },
    skipped: skipped.map((s) => ({
      brick: s.brick,
      part: s.part,
      reason: s.reason,
    })),
    generatedAt: new Date().toISOString(),
  };
  return { path: "manifest.json", contents: JSON.stringify(manifest, null, 2) + "\n" };
}

function emitReadme(): { path: string; contents: string } {
  const contents = `# UI8Kit Latte primitives

Generated by \`@ui8kit/codegen\` — **do not edit by hand**.

\`\`\`bash
# From ui8kit/codegen:
bun run generate:latte-bundle -- --out <path>

# From wp-fasty (after submodule / packages/ui8kit-codegen):
bun run ui:primitives
\`\`\`

## Layout

| Path | Role |
|------|------|
| \`ui/<brick>/<Part>.latte\` | Template primitives (60 of 63 parts) |
| \`ui/<brick>/*.variants.json\` | Shared CVA recipes (also embedded in Classes.php) |
| \`php/UI8Kit/Rt.php\` | Expression / tag helpers |
| \`php/UI8Kit/Classes.php\` | Class helpers for **all** parts (escape hatch) |
| \`composer.json\` | \`ui8kit/latte-primitives\` — Latte only |
| \`manifest.json\` | Coverage + skip reasons |

## Install

\`\`\`bash
composer install
\`\`\`

Point Latte \`FileLoader\` at \`ui/\` and autoload \`UI8Kit\\\\\` from \`php/UI8Kit/\`.

Skipped parts (\`Breadcrumb\`, \`Select\`, \`Icon\`) — use \`Classes::*\` helpers; see codegen docs \`docs/php-complex-parts.md\`.
`;
  return { path: "README.md", contents };
}

async function main(): Promise<void> {
  const out = parseOut(process.argv.slice(2));
  const files = await generateFiles(bricks, { runtimes: ["latte"] });

  // Drop parity harness + default dual-runtime composer; keep ui/ + php/UI8Kit/.
  const filtered = files.filter(
    (f) => !f.path.startsWith("cmd/") && f.path !== "composer.json"
  );

  filtered.push(emitLatteBundleComposerJson());
  filtered.push(emitManifest());
  filtered.push(emitReadme());

  await writeFiles(filtered, out);

  const skipped = phpSkippedParts(bricks);
  const total = bricks.reduce((n, b) => n + b.parts.length, 0);
  console.log(`Latte bundle: ${filtered.length} files → ${out}/`);
  console.log(`PHP parts: ${total - skipped.length}/${total} generated.`);
  for (const s of skipped) {
    console.log(`  skipped ${s.brick}/${s.part}: ${s.reason}`);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
