import {
  attrClass,
  attrExpr,
  attrRest,
  brick,
  cond,
  el,
  fwd,
  lit,
  oneOfOr,
  pAttrs,
  pBool,
  pChildren,
  pClass,
  pCva,
  pPass,
  prop,
  pSize,
  pStr,
  pVariant,
  slot,
} from "../_dsl";
import imageVariants from "./image.variants.json";

export default brick({
  id: "ui.image",
  dir: "image",
  docs:
    "Image renders accessible img, picture, and source primitives.\n" +
    "Use Decorative for purely visual images so alt stays empty.",
  recipes: { image: { file: "image.variants.json", recipe: imageVariants } },
  parts: [
    {
      name: "Image",
      docs: "Image renders an accessible img element.",
      recipeId: "image",
      classes: {
        recipe: {
          variant: "Variant",
          size: "Size",
          fit: "Fit",
          position: "Position",
          aspect: "Aspect",
        },
      },
      props: [
        pVariant(),
        pSize(),
        pClass(),
        pPass("Src"),
        pPass("SrcSet"),
        pPass("Sizes"),
        pStr("Alt", "alternative text; ignored when Decorative"),
        pPass("Width"),
        pPass("Height"),
        pCva("Fit", "fit", "object-fit preset"),
        pCva("Position", "position", "object-position preset"),
        pCva("Aspect", "aspect", "aspect-ratio preset"),
        pStr("Loading", "eager or lazy (default lazy)"),
        pStr("Decoding", "sync, auto, or async (default async)"),
        pPass("FetchPriority"),
        pBool("Decorative", "marks the image as purely presentational"),
        pPass("ID"),
        pAttrs(),
      ],
      render: el(
        "img",
        [
          fwd("src", "Src"),
          fwd("srcset", "SrcSet"),
          fwd("sizes", "Sizes"),
          attrExpr("alt", cond(prop("Decorative"), lit(""), prop("Alt")), { keepEmpty: true }),
          fwd("width", "Width"),
          fwd("height", "Height"),
          attrExpr("loading", oneOfOr(prop("Loading"), ["eager"], "lazy")),
          attrExpr("decoding", oneOfOr(prop("Decoding"), ["sync", "auto"], "async")),
          fwd("fetchpriority", "FetchPriority"),
          attrClass(),
          fwd("id", "ID"),
          attrExpr("aria-hidden", lit("true"), { when: prop("Decorative") }),
          attrRest(),
        ],
        [],
        { void: true }
      ),
    },
    {
      name: "Picture",
      docs: "Picture renders a responsive image wrapper.",
      classes: {},
      props: [pClass(), pAttrs(), pChildren()],
      render: el("picture", [attrClass(), attrRest()], [slot()]),
    },
    {
      name: "Source",
      docs: "Source renders a source candidate for picture, video, or audio.",
      props: [
        pPass("SrcSet"),
        pPass("Src"),
        pPass("Media"),
        pPass("Type"),
        pPass("Sizes"),
        pAttrs(),
      ],
      render: el(
        "source",
        [
          fwd("srcset", "SrcSet"),
          fwd("src", "Src"),
          fwd("media", "Media"),
          fwd("type", "Type"),
          fwd("sizes", "Sizes"),
          attrRest(),
        ],
        [],
        { void: true }
      ),
    },
  ],
});
